In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
pwd

'C:\\Users\\ebineet'

In [10]:
dataset= pd.read_csv(C:\Users\ebineet\Documents\Machine Learning\Data.csv)

SyntaxError: invalid syntax (<ipython-input-10-ba024cd0234b>, line 1)

In [18]:
dataset= pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Data.csv')

# Importing a DataSet 

In [4]:
## Importing a DataSet (Data.csv)

dataset= pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking Care of Missing Data

In [5]:
## Taking Care of Missing data in data set
## 1. Delete that particular row that has missing data.
## 2. Replace the missing value by the average of all the values in the column for which data is missing.

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding the Independent Varaible

In [6]:
## Encoding the Independent Variable:

# OneHotEncoding consists creating binary vectors for each column.So that there is no numerical order.
#Compose module and preprocessing module. 
#if passthrough is not used only the transformed column remains the rest does not remain.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x= np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding the Dependent Varaible

In [ ]:
#Encoding the Dependent Variable
#Encoding the last column YES or No
#LabelEncoder class

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)
print(y)


# Splitting the data into Training set and test set.
This is required for the futre machine learning model.




In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 1)
print(x_train)
print(x_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:
print(y_train)
print(y_test)

[0 1 0 0 1 1 0 1]
[0 1]


# Feature Scaling

Q.)
