# LOGISTIC REGRESSION

1. Importing the library
2. Importing the dataset
3. Splitting the dataset into TrainingSet and TestSet
4. Feature Scaling
5. Training the Logistic Regression Model on the training set
6. Prediction a new result
7. Prediction the test set result
8. Making the confusion Matrix
9. Visualizing the Training set result.
10. Visualizing the Test set result.

In [7]:
# Importing the library

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
# Importing the dataset

dataset= pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Machine+Learning+A-Z+(Codes+and+Datasets)\\Machine Learning A-Z (Codes and Datasets)\\Part 3 - Classification\\Section 14 - Logistic Regression\Python\\Social_Network_Ads.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [50]:
#Splitting the dataset into TrainingSet and TestSet

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.01)

In [51]:
print(x_test)

[[   51 23000]
 [   25 22000]
 [   32 18000]
 [   49 28000]]


In [52]:
print(y_test)

[1 0 0 1]


In [53]:
#Feature Scaling
# Actually not required in Logistic Reg but applying it will improve the performance of training set thus improve final pred
#  We do not apply feature scaling to y

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [54]:
from sklearn.linear_model import LogisticRegression
classifire= LogisticRegression()
classifire.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [58]:
#### Prediction a new result

print(classifire.predict(sc.transform([[25,22000]])))

[0]


In [61]:
#### Prediction the test set result

y_pred = classifire.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [0 1]]


In [62]:
## Making the confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2 0]
 [1 1]]


0.75

In [ ]:
#Visualising the training set result


In [ ]:
#Visualising the test set result