# Decision Trees

1. importing the library
2. reading and importing the training and testing dataset (here the dataset is split into two from before- train and test)
3. Feature Scaling
4. Training the Decission Tree model on training data set.
5. Predicting a new reult on train data and test data.
6. #Making the Confusion Matrix for training and testing data

In [1]:
# importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# read the dataset
train_data = pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Machine+Learning+A-Z+(Codes+and+Datasets)\\Machine Learning A-Z (Codes and Datasets)\\Part 3 - Classification\\Section 19 - Decision Tree Classification\\Python\\AnalyticsVidhya\\train-data.csv')
train_x = train_data.iloc[:, :-1].values
train_y = train_data.iloc[:, -1].values
test_data = pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Machine+Learning+A-Z+(Codes+and+Datasets)\\Machine Learning A-Z (Codes and Datasets)\\Part 3 - Classification\\Section 19 - Decision Tree Classification\\Python\\AnalyticsVidhya\\test-data.csv')
test_x = test_data.iloc[:, :-1].values
test_y = test_data.iloc[:, -1].values

In [4]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

In [5]:
#training the model
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(train_x, train_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [6]:
#Predicting the Test set results for training data
pred_train = classifier.predict(train_x)
#print(np.concatenate((pred_train.reshape(len(pred_train),1), train_y.reshape(len(train_y),1)),1))

In [7]:
#Predicting the Test set results for testing data
pred_test = classifier.predict(test_x)
#print(np.concatenate((pred_test.reshape(len(pred_test),1), test_y.reshape(len(test_y),1)),1))

In [8]:
#Making the Confusion Matrix for training data
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(train_y,pred_train)
print(cm)
accuracy_score(train_y,pred_train)

[[431   1]
 [  9 271]]


0.9859550561797753

In [9]:
#Making the Confusion Matrix for testing data
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(test_y, pred_test)
print(cm)
accuracy_score(test_y, pred_test)

[[94 23]
 [13 49]]


0.7988826815642458

# Random Forest

1. importing the library
2. reading and importing the training and testing dataset (here the dataset is split into two from before- train and test)
3. Feature Scaling
4. Training the Decission Tree model on training data set.
5. Predicting a new reult on train data and test data.
6. #Making the Confusion Matrix for training and testing data

In [19]:
# importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
# Reading and importing the training and testing dataset (here the dataset is split into two from before- train and test)

# read the dataset
train_data = pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Machine+Learning+A-Z+(Codes+and+Datasets)\\Machine Learning A-Z (Codes and Datasets)\\Part 3 - Classification\\Section 20 - Random Forest Classification\\Python\\AnalyticsVidhya\\train-data.csv')
train_x = train_data.iloc[:, :-1].values
train_y = train_data.iloc[:, -1].values
test_data = pd.read_csv('C:\\Users\\ebineet\\Documents\\Machine Learning\\Machine+Learning+A-Z+(Codes+and+Datasets)\\Machine Learning A-Z (Codes and Datasets)\\Part 3 - Classification\\Section 20 - Random Forest Classification\\Python\\AnalyticsVidhya\\test-data.csv')
test_x = test_data.iloc[:, :-1].values
test_y = test_data.iloc[:, -1].values

In [21]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

In [24]:
# Training the Decission Tree model on training data
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 2, criterion = 'entropy', random_state = 0)
classifier.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=2,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [25]:
#Predicting a new reult on train data.
pred_train = classifier.predict(train_x)

In [26]:
#Predicting a new reult on test data.
pred_test = classifier.predict(test_x)

In [27]:
#Making the Confusion Matrix for training data
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(train_y,pred_train)
print(cm)
accuracy_score(train_y,pred_train)

[[187   0]
 [ 17 508]]


0.976123595505618

In [28]:
#Making the Confusion Matrix for testing data
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(test_y,pred_test)
print(cm)
accuracy_score(test_y,pred_test)

[[ 58   0]
 [ 13 108]]


0.9273743016759777